name: sphinxdocs
channels:
  - defaults
dependencies:
  - alabaster=0.7.7
  - babel=2.2.0
  - conda=4.0.5
  - conda-env=2.4.5
  - decorator=4.0.9
  - docutils=0.12
  - flask=0.10.1
  - freetype=2.5.5
  - h5py=2.5.0
  - hdf5=1.8.15.1
  - ipython=4.1.2
  - ipython_genutils=0.1.0
  - itsdangerous=0.24
  - jbig=2.1
  - jinja2=2.8
  - markdown=2.6.5
  - markupsafe=0.23
  - matplotlib=1.4.3
  - nomkl=1.0
  - openssl=1.0.2g
  - path.py=8.1.2
  - pexpect=3.3
  - pickleshare=0.5
  - pillow=3.1.1
  - pip=8.1.0
  - pycosat=0.6.1
  - pycrypto=2.6.1
  - pygments=2.1.1
  - pyparsing=2.0.3
  - python=3.5.1
  - python-dateutil=2.4.2
  - pytz=2015.7
  - pyyaml=3.11
  - qt=4.8.7
  - readline=6.2
  - requests=2.9.1
  - scipy=0.16.0
  - setuptools=20.2.2
  - simplegeneric=0.8.1
  - six=1.10.0
  - snowballstemmer=1.2.1
  - sphinx=1.3.5
  - sphinx_rtd_theme=0.1.9
  - traitlets=4.1.0
  - wheel=0.29.0
  - xz=5.0.5=1
  - yaml=0.1.6=0
  - zlib=1.2.8=0
  - pyqt=4.11.4
  - sip=4.16.9
  - numpy=1.9.3
  - pep8=1.7.0
  - pyflakes=1.1.0
  - pyopengl=3.1.1a1
  - psutil=4.0.0
  - pip:
    - breathe==4.2.0
    - autopep8==1.2.2
    - qimage2ndarray==1.5
    - sphinx-py3doc-enhanced-theme>=2.3.2
    - sphinx-bootstrap-theme>=0.4.8
