name: sphinxdocs
channels:
  - defaults
dependencies:
  - python=3.5
  - pyqt=4.11.4
  - sip=4.16.9
  - numpy=1.9.3
  - pep8=1.7.0
  - pyflakes=1.1.0
  - pyopengl=3.1.1a1
  - psutil=4.0.0
  - sphinx=1.3
  - pip:
    - breathe==4.2.0
    - autopep8==1.2.2
    - qimage2ndarray==1.5
    - sphinx-py3doc-enhanced-theme>=2.3.2
    - sphinx-bootstrap-theme>=0.4.8
