name: sphinxdocs
channels:
  - defaults
dependencies:
  - alabaster=0.7.7=py35_0
  - babel=2.2.0=py35_0
  - conda=4.0.5=py35_0
  - conda-env=2.4.5=py35_0
  - decorator=4.0.9=py35_0
  - docutils=0.12=py35_0
  - flask=0.10.1=py35_1
  - freetype=2.5.5=0
  - h5py=2.5.0=np19py35_3
  - hdf5=1.8.15.1=2
  - ipython=4.1.2=py35_0
  - ipython_genutils=0.1.0=py35_0
  - itsdangerous=0.24=py35_0
  - jbig=2.1=0
  - jinja2=2.8=py35_0
  - jpeg=8d=1
  - libpng=1.6.17=0
  - libtiff=4.0.6=1
  - markdown=2.6.5=py35_0
  - markupsafe=0.23=py35_0
  - matplotlib=1.4.3=np19py35_3
  - mkl=11.3.1=0
  - nomkl=1.0=0
  - numpy=1.9.3=py35_nomkl_1
  - openssl=1.0.2g=0
  - path.py=8.1.2=py35_1
  - pep8=1.7.0=py35_0
  - pexpect=3.3=py35_0
  - pickleshare=0.5=py35_0
  - pillow=3.1.1=py35_0
  - pip=8.1.0=py35_0
  - psutil=4.0.0=py35_0
  - pycosat=0.6.1=py35_0
  - pycrypto=2.6.1=py35_0
  - pyflakes=1.1.0=py35_0
  - pygments=2.1.1=py35_0
  - pyopengl=3.1.1a1=np19py35_0
  - pyparsing=2.0.3=py35_0
  - pyqt=4.11.4=py35_1
  - python=3.5.1=0
  - python-dateutil=2.4.2=py35_0
  - python.app=1.2=py35_4
  - pytz=2015.7=py35_0
  - pyyaml=3.11=py35_1
  - qt=4.8.7=1
  - readline=6.2=2
  - requests=2.9.1=py35_0
  - scipy=0.16.0=np19py35_1
  - setuptools=20.2.2=py35_0
  - simplegeneric=0.8.1=py35_0
  - sip=4.16.9=py35_0
  - six=1.10.0=py35_0
  - snowballstemmer=1.2.1=py35_0
  - sphinx=1.3.5=py35_0
  - sphinx_rtd_theme=0.1.9=py35_0
  - sqlite=3.9.2=0
  - tk=8.5.18=0
  - traitlets=4.1.0=py35_0
  - werkzeug=0.11.4=py35_0
  - wheel=0.29.0=py35_0
  - xz=5.0.5=1
  - yaml=0.1.6=0
  - zlib=1.2.8=0
  - python=3.5
  - pyqt=4.11.4
  - sip=4.16.9
  - numpy=1.9.3
  - pep8=1.7.0
  - pyflakes=1.1.0
  - pyopengl=3.1.1a1
  - psutil=4.0.0
  - pip:
    - breathe==4.2.0
    - autopep8==1.2.2
    - qimage2ndarray==1.5
    - sphinx-py3doc-enhanced-theme>=2.3.2
    - sphinx-bootstrap-theme>=0.4.8
